#include "openclutils.hpp"

#include <iostream>

ThreeDL::OpenCLUtils::OpenCLUtils() {
    // Look for platforms that may contain devices (GPUs)
    cl::Platform::get(&platforms_);
    if (platforms_.empty()) {
        throw std::runtime_error("No OpenCL platforms found");
    }

    // Select platform that contains required GPU
    platform_ = platforms_[1];
    std::cout << "Using platform: " << platform_.getInfo<CL_PLATFORM_NAME>() << std::endl;

    // Get all devices held by a platform
    platform_.getDevices(CL_DEVICE_TYPE_ALL, &devices_);
    if (devices_.empty()) {
        throw std::runtime_error("No OpenCL devices found");
    }

    // Select GPU which will be used to render scene
    device_ = devices_[0];
    std::cout << "Using device: " << device_.getInfo<CL_DEVICE_NAME>() << std::endl;

    // get mem size in GB
    cl_ulong mem_size;
    device_.getInfo(CL_DEVICE_GLOBAL_MEM_SIZE, &mem_size);
    std::cout << "Global memory size: " << mem_size / (1024 * 1024 * 1024) << " GB" << std::endl;

    context_ = cl::Context({device_});

    // Create queue to which all instructions will be submitted
    queue_ = cl::CommandQueue(context_, device_);
}

std::string ThreeDL::OpenCLUtils::readKernel() {
    /*
       Include file that contains the 'kernel_include_source' variable. This file
       is generated by the iact.py file. This variable contains all of the GPU
       source code.
    */
    #include "iact.h"
    return kernel_include_source;
}

cl::Program ThreeDL::OpenCLUtils::buildProgram() const {
    // Create an executable code from GPU source code in file
    cl::Program program (context_, { readKernel() });

    // compile the OpenCL program
    if (program.build(devices_) != CL_SUCCESS) {
        throw std::runtime_error(program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(device_));
    }

    return program;
}

bool ThreeDL::OpenCLUtils::checkSVMCompatibility() const {
    return device_.getInfo<CL_DEVICE_SVM_CAPABILITIES>() & CL_DEVICE_SVM_COARSE_GRAIN_BUFFER;
}